# .slather.yml

coverage_service: coveralls
xcodeproj: Example/EasyRealm.xcodeproj
workspace: Example/EasyRealm.xcworkspace
scheme: EasyRealm-Example
source_directory: Pod/Classes
binary_basename: EasyRealm
input_format: profdata
