language: objective-c
osx_image: xcode8.2
xcode_project: Example/EasyRealm.xcworkspace
before_install:
  - gem install slather --no-rdoc --no-ri --no-document --quiet
  - gem install fastlane -NV
before_script:
#If one of this failed we have error and all process is stopped
- cd Example
- pod install --repo-update

script:
- fastlane scan -s EasyRealm-Example --device "iPhone 6" --clean --code_coverage

after_success:
- cd $TRAVIS_BUILD_DIR && slather
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true
